# Generated by Django 3.0.4 on 2022-06-19 17:36

from django.db import migrations, models
import django_resized.forms
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='boolean',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='float',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('mexico', 'Mexico'), ('argentina', 'Argentina'), ('colombia', 'Colombia')], default='Mexico', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_profile.jpg', force_format=None, keep_meta=True, quality=-1, size=[300, 300], upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intrests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('c', 'Coding'), ('r', 'Reading'), ('t', 'Trading'), ('g', 'Gaming')], max_length=7),
        ),
    ]
